name: Filament v3 tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3]
        laravel: ["10.*", "11.*"]
        stability: [prefer-stable]
        include:
          - php: 8.2
            laravel: 10.*
            stability: prefer-lowest

    name: PHP ${{ matrix.php }} · Laravel ${{ matrix.laravel }} · Filament 3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer require \
            filament/filament:^3.0 \
            laravel/framework:${{ matrix.laravel }} \
            --no-update

          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/pest --ci
